# ----------------------------------------------------------
# Author: Nandan Kumar
# Date: 10/20/2025
# Project: IS601 Midterm - Enhanced Calculator
# ----------------------------------------------------------
# GitHub Actions CI Workflow
# Purpose:
#   Automatically runs pytest with coverage on every
#   push or pull request to the main branch.
#   Enforces minimum 90% code coverage to maintain quality.
# ----------------------------------------------------------

name: Run Tests on Push or Pull Request to Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Pytest with Coverage Check

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set Up Python Environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov pandas python-dotenv

      # 4. Run Unit Tests with Coverage Enforcement
      - name: Run Tests and Enforce 90 Percent Coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q \
                 --cov=app --cov-report=term-missing \
                 --cov-report=xml --cov-fail-under=90
